#
# WARNING_: This file is automatically generated by CMake and any manual changes will
# be overridden by the next build.
# If you need to change anything here, please update the configure template BBuildEnvVersion.cmake.in.
#

set( BBuildEnv_VERSION_MAJOR 3 )
set( BBuildEnv_VERSION_MINOR 14 ) 
set( BBuildEnv_VERSION_PATCH 4 ) 
set( BBuildEnv_VERSION_TWEAK 4 )

# BBuildEnv version in decimal dotted format as supported by CMake's version compare operations.
set( BBuildEnv_VERSION "${BBuildEnv_VERSION_MAJOR}.${BBuildEnv_VERSION_MINOR}.${BBuildEnv_VERSION_PATCH}.${BBuildEnv_VERSION_TWEAK}" ) 
